; ESP8266 PhantomKit - PlatformIO Configuration
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps = 
    ESP8266WiFi
    DNSServer
    ESP8266WebServer
    ESP8266HTTPClient
    bblanchon/ArduinoJson @ ^6.21.3
